---
name: 'GitHub Algorithm Practicing Reminder Bot'

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  serverchan:
    name: Server chan
    runs-on: ubuntu-latest
    steps:
      - name: 'Get LeetCode Problems'
        run: echo "::set-env name=FILES::$(find ./ -name "*.py")"
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: Sending message
        uses: yakumioto/serverchan-action@v1
        with:
          key: ${{ secrets.SCKEY }}
          text: 五毒神掌 の (${{env.REPORT_DATE}})
          desp: file://${{ env.FILES }}
